"""describe your change

Revision ID: 1ca2a0b151f7
Revises: a87092c4cf57
Create Date: 2025-12-17 22:39:19.946531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1ca2a0b151f7'
down_revision: Union[str, Sequence[str], None] = 'a87092c4cf57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'thread_id',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.drop_index(op.f('sha256_hash'), table_name='documents')
    op.create_unique_constraint('uq_thread_file', 'documents', ['thread_id', 'sha256_hash'])
    op.drop_constraint(op.f('documents_ibfk_1'), 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'threads', ['thread_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('documents_ibfk_1'), 'documents', 'threads', ['thread_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('uq_thread_file', 'documents', type_='unique')
    op.create_index(op.f('sha256_hash'), 'documents', ['sha256_hash'], unique=True)
    op.alter_column('documents', 'thread_id',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###
