"""initial schema2

Revision ID: 37bce259f3f9
Revises: 6e20d864a42b
Create Date: 2026-01-04 20:38:55.184794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37bce259f3f9'
down_revision: Union[str, Sequence[str], None] = '6e20d864a42b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_memory_settings', sa.Column('allow_long_conversation_memory', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_memory_settings', 'allow_long_conversation_memory')
    # ### end Alembic commands ###
