"""add status to user_tools

Revision ID: 52ef4bc07d62
Revises: a0566b71d383
Create Date: 2025-12-02 03:31:32.274199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52ef4bc07d62'
down_revision: Union[str, Sequence[str], None] = 'a0566b71d383'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tools', sa.Column('status', sa.Enum('active', 'inactive', name='tool_status'), server_default='active', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tools', 'status')
    # ### end Alembic commands ###
