"""initial schema

Revision ID: 6e20d864a42b
Revises: 
Create Date: 2026-01-04 19:09:28.418942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6e20d864a42b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('semantic_embeddings', sa.Column('semantic_memory_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('embedding_id'), table_name='semantic_embeddings')
    op.drop_index(op.f('idx_semantic_embedding_id'), table_name='semantic_embeddings')
    op.create_index(op.f('ix_semantic_embeddings_semantic_memory_id'), 'semantic_embeddings', ['semantic_memory_id'], unique=True)
    op.create_foreign_key(None, 'semantic_embeddings', 'semantic_memories', ['semantic_memory_id'], ['id'], ondelete='CASCADE')
    op.drop_column('semantic_embeddings', 'embedding_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('semantic_embeddings', sa.Column('embedding_id', mysql.VARCHAR(length=36), nullable=False))
    op.drop_constraint(None, 'semantic_embeddings', type_='foreignkey')
    op.drop_index(op.f('ix_semantic_embeddings_semantic_memory_id'), table_name='semantic_embeddings')
    op.create_index(op.f('idx_semantic_embedding_id'), 'semantic_embeddings', ['embedding_id'], unique=False)
    op.create_index(op.f('embedding_id'), 'semantic_embeddings', ['embedding_id'], unique=True)
    op.drop_column('semantic_embeddings', 'semantic_memory_id')
    # ### end Alembic commands ###
