"""add status to user_tools

Revision ID: a0566b71d383
Revises: 96e954003708
Create Date: 2025-12-02 03:15:18.374314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0566b71d383'
down_revision: Union[str, Sequence[str], None] = '96e954003708'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tools', sa.Column('status', sa.Enum('allowed', 'denied', name='user_tool_status'), server_default='allowed', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_tools', 'status')
    # ### end Alembic commands ###
